### ISSUE TITLE
Web has no mounted volumes

### ISSUE THREAD

**Issue by zerkei** [heroku/docker-php#1]
It looks like you might have forgotten to add this:
volumes:
      - '.:/app/user'
To web

**Comment by boboldehampsink** [comment]
Live editing does not work because of this

**Comment by boboldehampsink** [comment]
I have created a PR here: https://github.com/heroku/heroku-docker/pull/128

**Comment by jmccartie** [comment]
Closing this issue. We're making some changes on how we (Heroku) best support docker builds. We have some exciting things planned, but need to clear out some existing issues at this time. Thanks!
