### ISSUE TITLE
When using nginx, file uploads are not supported and fail with a permission denied to the "client_body_temp" directory

### ISSUE THREAD

**Issue by busbyjon** [heroku/docker-php#10]
# Expected Behaviour

File uploads should occur as normal, uploading to the "client_body_temp" dir before being processed by PHP.  

# Observed Behaviour

When performing a file upload the following occurs

"104#0: *1 open() "/app/.heroku/php//var/run/nginx/client_body_temp/0000000001" failed (13: Permission denied),"...

Although the directory of "/app/.heroku/php//var/run/nginx/client_body_temp" has the correct permissions, its parent folders do not.  To resolve these folders need their owners resetting, or their permissions opening up to allow nginx to write here.

**Comment by boboldehampsink** [comment]
I fixed this by adding 
```
client_max_body_size 20M;
client_body_temp_path /tmp/client_body_tmp;
```

to the nginx conf

**Comment by friism** [comment]
@dzuelke ^

**Comment by busbyjon** [comment]
@boboldehampsink @friism - did you see my PR?

**Comment by jmccartie** [comment]
@busbyjon Closing this issue. We're making some changes on how we (Heroku) best support docker builds. We have some exciting things planned, but need to clear out some existing issues at this time. Thanks!
