### ISSUE TITLE
Add memcached and redis extension support

### ISSUE THREAD

**Issue by boboldehampsink** [heroku/docker-php#13]
On Heroku, we can use `ext-redis` and  `ext-memcached` - should they be default in this Docker image?

**Comment by boboldehampsink** [comment]
Any updates?

**Comment by jmccartie** [comment]
@boboldehampsink @DaGhostman Sorry for the delay here. We're making some changes on how we (Heroku) best support docker builds. We have some exciting things planned, but need to clear out some existing issues at this time. As such we'll be closing this issue until we're ready to support this repo. Thanks!
