### ISSUE TITLE
Add ability to overwrite PHP_VERSION, HTTPD_VERSION and NGINX_VERSION vars 

### ISSUE THREAD

**Issue by boboldehampsink** [heroku/docker-php#15]
Please add the ability to overwrite PHP_VERSION, HTTPD_VERSION and NGINX_VERSION vars.
They are now set with ENV, which can't be overwritten. Use ARG instead: https://docs.docker.com/engine/reference/builder/#arg

**Comment by jmccartie** [comment]
Closing this issue. We're making some changes on how we (Heroku) best support docker builds. We have some exciting things planned, but need to clear out some existing issues at this time. Thanks!
