### ISSUE TITLE
Service "shell" doesn't have any configuration options

### ISSUE THREAD

**Issue by theunorthodoxdeveloper** [heroku/docker-php#2]
I have run the commands as outlined and when I try to run 

`docker-compose up web`

It displays the following error: 

*Service "shell" doesn't have any configuration options. All top level keys in your docker-compose.yml must map to a dictionary of configuration options.*

**Comment by boboldehampsink** [comment]
Can you post your `docker-compose.yml` file contents?

**Comment by jmccartie** [comment]
Closing this issue. We're making some changes on how we (Heroku) best support docker builds. We have some exciting things planned, but need to clear out some existing issues at this time. Thanks!
