### ISSUE TITLE
heroku docker:release error

### ISSUE THREAD

**Issue by boboldehampsink** [heroku/docker-php#6]
Hi,

When doing `heroku docker:release` the application gets released succesfully, but crashes on Heroku with the following output:

```bash
Sep 30 06:10:06 ... heroku/web.1:  Starting process with command `cd /app/user && vendor/bin/heroku-php-apache2` 
Sep 30 06:10:09 ... app/web.1:  bash: vendor/bin/heroku-php-apache2: No such file or directory 
Sep 30 06:10:10 ... heroku/web.1:  State changed from starting to crashed 
Sep 30 06:10:10 ... heroku/web.1:  Process exited with status 127 
```

**Comment by friism** [comment]
Hm, this might be an issue better reported on @heroku/docker-php /cc @dzuelke

**Comment by boboldehampsink** [comment]
This is @heroku/docker-php

**Comment by friism** [comment]
Sorry, I'm an idiot.

**Comment by boboldehampsink** [comment]
This issue is totally blocking heroku docker use for me. How alive is this project?

**Comment by friism** [comment]
Sorry, I'll take a look and test this tmrw

**Comment by boboldehampsink** [comment]
With a node/php multipack configuration that works with normal deployment, I now get these errors with docker:release

```bash
Oct 14 01:50:37 ... heroku/api:  Release v16 created by ...
Oct 14 01:50:37 ... heroku/web.1:  State changed from crashed to starting 
Oct 14 01:50:49 ... heroku/web.1:  Starting process with command `cd /app/user && vendor/bin/heroku-php-apache2` 
Oct 14 01:50:51 ... app/web.1:  vendor/bin/heroku-php-apache2: line 196: -dnewrelic.enabled=0: command not found 
Oct 14 01:50:51 ... app/web.1:  This program requires PHP 5.5.11 or newer; check your 'php' command. 
Oct 14 01:50:52 ... heroku/web.1:  Process exited with status 1 
Oct 14 01:50:52 ... heroku/web.1:  State changed from starting to crashed

**Comment by alfredtan** [comment]
Hello, 

Was there any solution for this? I'm new to Docker & Heroku. Docker runs well on my local machine but i'm getting similar errors on Heroku:

```
$ heroku logs --tail
2016-03-11 heroku[web.1]: Starting process with command `cd /app/user && vendor/bin/heroku-php-nginx`
2016-03-11 app[web.1]: This program requires PHP 5.5.11 or newer; check your 'php' command.
2016-03-11 app[web.1]: vendor/bin/heroku-php-nginx: line 196: php: command not found
2016-03-11 heroku[web.1]: Process exited with status 1
```

Seems that `php` is not found on Heroku:
```
$ heroku run "php -v"
Running php -v on stormy-spire-92196... up, run.5808
bash: php: command not found
```

But in my local docker container's shell, I can get the php version:
```
$ docker-compose run shell
root@e21f0ebf760b:/app/user# php -v
PHP 5.6.15 (cli) (built: Oct 30 2015 22:01:21) 
Copyright (c) 1997-2015 The PHP Group
```

**Comment by mikamix** [comment]
Hi, I had same issue. guess "ENV PATH /app/.heroku/php/bin:/app/.heroku/php/sbin:$PATH" is not working. I set PATH to heroku config vars like "heroku config:set PATH=/app/.heroku/php/bin:/app/.heroku/php/sbin:/usr/local/bin:/usr/bin:/bin" and work fine.

**Comment by jmccartie** [comment]
Closing this issue. We're making some changes on how we (Heroku) best support docker builds. We have some exciting things planned, but need to clear out some existing issues at this time. Thanks!
