### ISSUE TITLE
`docker-compose up web` fails to start container after first run

### ISSUE THREAD

**Issue by mars** [heroku/docker-php#7]
Following the [Build and Deploy with Docker: Getting Started](https://devcenter.heroku.com/articles/docker#getting-started) instructions for a PHP app:

* The first `docker-compose up web` succeeds, and I can connect to the web app running in the Docker container.

  ```
$ docker-compose up web
Creating illuminatethearts_mysql_1...
Creating illuminatethearts_web_1...
Attaching to illuminatethearts_web_1
web_1 | DOCUMENT_ROOT changed to 'web/'
web_1 | 4 processes at 128MB memory limit.
web_1 | Starting php-fpm...
web_1 | Starting httpd...
web_1 | Application ready for connections on port 8080.
  ```
* When I control + c once to terminate, the output is suspicious:

  ```
^CGracefully stopping... (press Ctrl+C again to force)
Stopping illuminatethearts_web_1... done

Aborting.
  ```
* Subsequent attempts to run `docker-compose up web` fail:

  ```
web_1 | httpd (pid 103) already running
web_1 | Process exited unexpectedly: httpd
web_1 | Going down, terminating child processes...
illuminatethearts_web_1 exited with code 1
Gracefully stopping... (press Ctrl+C again to force)
  ```
* Despite the log output saying "httpd (pid 103) already running," the docker process listing shows that the container is stopped:

  ```
$ docker-compose ps
          Name                         Command               State     Ports   
------------------------------------------------------------------------------
illuminatethearts_mysql_1   /entrypoint.sh mysqld            Up       3306/tcp 
illuminatethearts_web_1     bash -c vendor/bin/heroku- ...   Exit 1
  ```

**Comment by boboldehampsink** [comment]
I'm experiencing this problem too. It's really annoying to have to rebuild your image every time you want to start it. It should be fixed that when you stop the container, httpd stops too.

**Comment by dzuelke** [comment]
This is weird; doesn't happen for me:

```
$ docker-compose up web
Recreating dockertest1_web_1...
Attaching to dockertest1_web_1
web_1 | 4 processes at 128MB memory limit.
web_1 | Starting php-fpm...
web_1 | Starting httpd...
web_1 | Application ready for connections on port 8080.
^CGracefully stopping... (press Ctrl+C again to force)
Stopping dockertest1_web_1...

Aborting.
$ docker-compose up web
Recreating dockertest1_web_1...
Attaching to dockertest1_web_1
web_1 | 4 processes at 128MB memory limit.
web_1 | Starting php-fpm...
web_1 | Starting httpd...
web_1 | Application ready for connections on port 8080.
^CGracefully stopping... (press Ctrl+C again to force)
Killing dockertest1_web_1...
```

What versions of Docker are y'all on?

**Comment by boboldehampsink** [comment]
```bash
docker -v
Docker version 1.8.2, build 0a8c2e3
```

**Comment by mars** [comment]
$ docker -v
    Docker version 1.8.2, build 0a8c2e3

**Comment by dzuelke** [comment]
Okay, happens to me now after an upgrade from Docker 1.7 to 1.8.

**Comment by dzuelke** [comment]
Hi @mars, could you please change the `require-dev` dependency for `heroku/heroku-buildpack-php` to version `dev-develop` temporarily, rebuild, and see if that fixes the problem? Thanks!

**Comment by dzuelke** [comment]
Just updated again, so try now. More issues fixed.

You need to run `composer update` of course after changing the version from `*` to `dev-develop` in `composer.json`, to re-generate `composer.lock`.

Works for me now:

```
docker-test-1 $ docker-compose up web
Creating dockertest1_web_1
Attaching to dockertest1_web_1
web_1 | 4 processes at 128MB memory limit.
web_1 | Starting php-fpm...
web_1 | Starting httpd...
web_1 | Application ready for connections on port 8080.
^CGracefully stopping... (press Ctrl+C again to force)
Stopping dockertest1_web_1 ... done
ERROR: 
Aborting.


docker-test-1 $ docker-compose up web
Starting dockertest1_web_1
Attaching to dockertest1_web_1
web_1 | 4 processes at 128MB memory limit.
web_1 | Starting php-fpm...
web_1 | Starting httpd...
web_1 | Application ready for connections on port 8080.
```

**Comment by mars** [comment]
Yes indeed, that fixes it for me: `heroku/heroku-buildpack-php (dev-develop d6a4f58)`

**Comment by dzuelke** [comment]
Alright, fixed. Make sure you have `*` again as the version selector, `composer update`, and `docker pull heroku/php` before you rebuild while you're at it.

**Comment by mars** [comment]
:cake:
