### ISSUE TITLE
Opcache and local development

### ISSUE THREAD

**Issue by boboldehampsink** [heroku/docker-php#8]
Is there a way we can disable opcache for local development?

**Comment by dzuelke** [comment]
I re-enabled checks and set the invalidate frequency to 0. See if that helps please!

**Comment by boboldehampsink** [comment]
Ok. Are your Dockerfiles automatically building on Docker Hub? In that case, i'll wait a few more minutes untill it becomes ready.

**Comment by dzuelke** [comment]
Yup, they are! Should be done now: https://hub.docker.com/r/heroku/php/builds/

**Comment by boboldehampsink** [comment]
Have updated and will be testing this with my team tomorrow. Thanks in advance!

**Comment by friism** [comment]
Thanks @boboldehampsink!
